name: Auto Pull on Server Branch

on:
  push:
    branches:
      - server  # Change this to the branch you want to auto-deploy
  workflow_dispatch:  # This adds a manual trigger

jobs:
  deploy:
    runs-on: self-hosted  # This will run on your self-hosted runner

    steps:
      - name: Pull latest code on server branch
        run: |
          cd /home/unchiipecos/api-pdf-gemini  # Replace with the actual path to your repository
          git fetch origin server
          git reset --hard origin/server
          
      - name: Run dependencies and update them
        run: |
          cd /home/unchiipecos/api-pdf-gemini
          source venv/bin/activate
          pip freeze > requirements.txt  # Update requirements.txt with the latest dependencies
          pip install -r requirements.txt
          deactivate
      - name: Set up Environment
        env:
          APP_SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          DOTNET_USER_PASSWORD: ${{ secrets.DOTNET_USER_PASSWORD }}
        run: |
          echo "done"
        
      - name: Restart server
        run: |
          sudo systemctl restart flask_gunicorn  # Optional: restart the Gunicorn service
